version: '3.7'
services:
  dev:
    build:
      target: dev
      context: .
      dockerfile: ci-cd/docker/Dockerfile
      args:
        - IMAGE_VERSION=9.0.5
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: ci-cd/docker/scripts/start.sh
    ports:
    - "8000:8000"
    volumes: 
      - ./:/home/developer/workspace
      - vscode-server-extensions:/root/.vscode-server/extensions
      - dev-bashhistory:/commandhistory
      - vscode-server-insiders-extensions:/root/.vscode-server-insiders/extensions
volumes:
  vscode-server-extensions:
  vscode-server-insiders-extensions:
  dev-bashhistory: